name: statsd
version: 0.1.0
description: statsd client for Dart
homepage: https://github.com/pulyaevskiy/dart-statsd
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  logging: "^0.11.2"

dev_dependencies:
  test: "^0.12.6+1"
  mockito: "^0.11.0"
  dart_coveralls: "^0.4.0"
